<?php

namespace Database\Seeders;
use App\Models\Student;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        Student::create([
            'group_id'=>1,
            'name'=>'ALpamis',
            'phone'=>99988718,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>2,
            'name'=>'Dawran',
            'phone'=>9998584,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>3,
            'name'=>'ASad',
            'phone'=>99984688,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>4,
            'name'=>'Nurlan',
            'phone'=>999845688,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>5,
            'name'=>'Aybergen',
            'phone'=>999886458,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>6,
            'name'=>'Nurali',
            'phone'=>9994888,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>7,
            'name'=>'Azamat',
            'phone'=>99986588,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>8,
            'name'=>'Sultan',
            'phone'=>912888,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>9,
            'name'=>'Nursultan',
            'phone'=>99982188,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>10,
            'name'=>'Miyras',
            'phone'=>99982188,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>1,
            'name'=>'ALpamis',
            'phone'=>9998488,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>2,
            'name'=>'Dawran',
            'phone'=>999888,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>3,
            'name'=>'ASad',
            'phone'=>99964888,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>4,
            'name'=>'Nurlan',
            'phone'=>999864488,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>5,
            'name'=>'Aybergen',
            'phone'=>999888,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>6,
            'name'=>'Nurali',
            'phone'=>999882118,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>7,
            'name'=>'Azamat',
            'phone'=>99988248,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>8,
            'name'=>'Sultan',
            'phone'=>9123898,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>9,
            'name'=>'Nursultan',
            'phone'=>999884668,
            'password'=>123
        ]);
        Student::create([
            'group_id'=>10,
            'name'=>'Miyras',
            'phone'=>99988698,
            'password'=>123
        ]);
    }
}
